apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: task-operator
  template:
    metadata:
      labels:
        name: task-operator
    spec:
      serviceAccountName: task-operator
      containers:
        - name: task-operator
          image: ukocasarac/task-operator:1
          command:
          - task-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "task-operator"
